name: Build and test
on:
  pull_request:
    branches:
      - main

jobs:
  configure_env:
    name: Configure environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: composer install --no-ansi --no-interaction --optimize-autoloader --no-progress

      - run: npm clean-install
      - run: npm run build --if-present

      - run: composer run-script test
      - run: npm run test --if-present